version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/server
    overwrite: yes
permissions:
  - object: /home/ubuntu/server/
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:

  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: scripts/deploy.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: scripts/health.sh
      timeout: 60
      runas: root