name: Docker Image CI

on: #이벤트다. 이벤트가 발생해야 워크 플로우를 실행한다.
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Make main application.yml
        run: |
          cd ./src/main/resources
          echo "${{ secrets.MAIN_APPLICATION_YML }}" >> ./application.yml
        shell: bash

      - name: boot Jar
        run: ./gradlew bootJar

      - name: Build Application
        run: ./gradlew build

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: aws 세팅
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://${{ secrets.S3_BUCKET }}/deploy/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name wayc-code-deploy --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name wayc-ci-cd-group --s3-location bucket=${{ secrets.S3_BUCKET }},bundleType=zip,key=deploy/$GITHUB_SHA.zip
