name: Docker Image CI

on: #이벤트다. 이벤트가 발생해야 워크 플로우를 실행한다.
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Make main application.yml
      run: |
        cd ./src/main/resources
        echo "${{ secrets.MAIN_APPLICATION_YML }}" >> ./application.yml
      shell: bash

    - name: Build Application
      run: ./gradlew clean build -x test #테스트 실행을 하지 않음.

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_ADDRESS }}/${{ secrets.DOCKER_REPO }} .

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_ADDRESS }}/${{ secrets.DOCKER_REPO }}

    - name: Executing remote ssh command using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.REMOTE_SSH_ID }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          sudo docker stop $(sudo docker ps -qa)
          sudo docker rm $(sudo docker ps -qa)
          sudo docker pull ${{ secrets.DOCKER_ADDRESS }}/${{ secrets.DOCKER_REPO }}
          sudo docker run -p ${{ secrets.SERVER_PORT }}:${{ secrets.DOCKER_PORT }} ${{ secrets.DOCKER_ADDRESS }}/${{ secrets.DOCKER_REPO }}
## ec2 접속후 도커 이미지를 pull해서 컨테이너를 실행해 띄운다.